dist: xenial
language: python
python:
  - "3.7"
  - "3.8"

install:
  # Install conda
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -y -n base conda setuptools
  - conda create -n usgdp-npp-dev python=$TRAVIS_PYTHON_VERSION
  - source activate usgdp-npp-dev
  - conda env update -f environment.yml
  - CODECOV_TOKEN="841f2d0d-c2d1-45c1-8e81-c37744d95b21"

# command to run tests, e.g. python setup.py test
script:
  - coverage run -m pytest -s -v

after_success:
  - codecov
